package Ventanas;

import Formularios.RegistrarCosecha;
import Formularios.RegistrarCompra;
import Formularios.RegistrarConsumo;
import Formularios.RegistrarProducto;
import Formularios.RegistrarProveedor;
import Formularios.Reportes;
import Formularios_emergentes.Fmr_ListadoArea;
import Formularios_emergentes.Fmr_ListadoCosechas;
import Formularios_emergentes.Fmr_ListadoProductos;
import Formularios_emergentes.Fmr_ListadoProveedores;
import Formularios_emergentes.Fmr_ListadoCompras;
import Formularios_emergentes.Fmr_ListadoConsumos;
import V_RegistrarProductos.Fmr_ListadoUnidadmedida;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Graphics;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Osiris
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();

        this.setTitle("AgroControl - Menu Principal");
        this.setLocationRelativeTo(null);
        setResizable(false);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));

        return retValue;
    }

    public void salir() {

        Login inicio = new Login();
        inicio.setVisible(true);
        this.dispose();
    }

    public boolean JInternalFrames_Abiertos(JInternalFrame jif) {
        // Creamos un metodo publico de tipo boolean.
        JInternalFrame[] jif_Activos = MenuPrincipal.mostrar.getAllFrames();
        // Este arreglo almacena todos los JInternalFrames que esten abierto en el jDesktopPane.

        for (int i = 0; i < jif_Activos.length; i++) {
            // Creamos un ciclo for para recorrer nuestro arreglo utilizando la propiedad length de nuestro arreglo.

            // Validamos con un if si nuestro arreglo en la posición i es igual al JInternalFrame que esta activo en el jDesktopPane, si es igual devolverá true.
            if (jif.getClass().isInstance(jif_Activos[i])) {
                return true;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/Imagenes/fondo-menu.jpg"));
        Image image1 = icon1.getImage();
        Escritorio = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image1,0,0,getWidth(),getHeight(),this);
            }
        };
        lbl_logo = new javax.swing.JLabel();
        lbl_cosecha = new javax.swing.JLabel();
        lbl_proveedores = new javax.swing.JLabel();
        lbl_salir = new javax.swing.JLabel();
        lbl_consumos = new javax.swing.JLabel();
        lbl_compras = new javax.swing.JLabel();
        lbl_productos = new javax.swing.JLabel();
        lbl_reportes = new javax.swing.JLabel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagenes/fondo-ventana.png"));
        Image image = icon.getImage();
        mostrar = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMI_RProveedor = new javax.swing.JMenuItem();
        jMI_RProducto = new javax.swing.JMenuItem();
        jMI_RCompra = new javax.swing.JMenuItem();
        jMI_RConsumo = new javax.swing.JMenuItem();
        jMI_RCosecha = new javax.swing.JMenuItem();
        jMI_Salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMI_LProveedores = new javax.swing.JMenuItem();
        jMI_LProductos = new javax.swing.JMenuItem();
        jMI_LCompras = new javax.swing.JMenuItem();
        jMI_LConsumos = new javax.swing.JMenuItem();
        jMI_LCosechas = new javax.swing.JMenuItem();
        jMI_LAreas = new javax.swing.JMenuItem();
        jMI_LUnidaddeMedida = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));

        Escritorio.setBackground(new java.awt.Color(240, 255, 240));
        Escritorio.setPreferredSize(new java.awt.Dimension(1280, 720));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-login.png"))); // NOI18N

        lbl_cosecha.setBackground(new java.awt.Color(255, 255, 255));
        lbl_cosecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_cosecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cosecha.png"))); // NOI18N
        lbl_cosecha.setText("Cosecha");
        lbl_cosecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl_cosecha.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbl_cosecha.setOpaque(true);
        lbl_cosecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cosechaMouseClicked(evt);
            }
        });

        lbl_proveedores.setBackground(new java.awt.Color(255, 255, 255));
        lbl_proveedores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proveedor.png"))); // NOI18N
        lbl_proveedores.setText("Proveedores");
        lbl_proveedores.setToolTipText("");
        lbl_proveedores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl_proveedores.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbl_proveedores.setOpaque(true);
        lbl_proveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_proveedoresMouseClicked(evt);
            }
        });

        lbl_salir.setBackground(new java.awt.Color(255, 255, 255));
        lbl_salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        lbl_salir.setText("Salir");
        lbl_salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl_salir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbl_salir.setOpaque(true);
        lbl_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_salirMouseClicked(evt);
            }
        });

        lbl_consumos.setBackground(new java.awt.Color(255, 255, 255));
        lbl_consumos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_consumos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Consumo.png"))); // NOI18N
        lbl_consumos.setText("Consumos");
        lbl_consumos.setToolTipText("");
        lbl_consumos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl_consumos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbl_consumos.setOpaque(true);
        lbl_consumos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_consumosMouseClicked(evt);
            }
        });

        lbl_compras.setBackground(new java.awt.Color(255, 255, 255));
        lbl_compras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Compra.png"))); // NOI18N
        lbl_compras.setText("Compras");
        lbl_compras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl_compras.setOpaque(true);
        lbl_compras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_comprasMouseClicked(evt);
            }
        });

        lbl_productos.setBackground(new java.awt.Color(255, 255, 255));
        lbl_productos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Productos.png"))); // NOI18N
        lbl_productos.setText("Productos");
        lbl_productos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl_productos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbl_productos.setOpaque(true);
        lbl_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_productosMouseClicked(evt);
            }
        });

        lbl_reportes.setBackground(new java.awt.Color(255, 255, 255));
        lbl_reportes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reporte.png"))); // NOI18N
        lbl_reportes.setText("Reportes");
        lbl_reportes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl_reportes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbl_reportes.setOpaque(true);
        lbl_reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_reportesMouseClicked(evt);
            }
        });

        mostrar.setBackground(new java.awt.Color(240, 255, 240));
        mostrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mostrar.setForeground(new java.awt.Color(240, 255, 240));
        mostrar.setAutoscrolls(true);
        mostrar.setMaximumSize(new java.awt.Dimension(800, 600));
        mostrar.setMinimumSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout mostrarLayout = new javax.swing.GroupLayout(mostrar);
        mostrar.setLayout(mostrarLayout);
        mostrarLayout.setHorizontalGroup(
            mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        mostrarLayout.setVerticalGroup(
            mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        Escritorio.setLayer(lbl_logo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(lbl_cosecha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(lbl_proveedores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(lbl_salir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(lbl_consumos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(lbl_compras, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(lbl_productos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(lbl_reportes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(mostrar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EscritorioLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_proveedores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_productos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_compras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_consumos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_reportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_cosecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(EscritorioLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lbl_logo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EscritorioLayout.createSequentialGroup()
                        .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(lbl_proveedores)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_productos)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_compras)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_cosecha)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_consumos)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_reportes)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_salir)))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        jMI_RProveedor.setText("Registrar Proveedor");
        jMI_RProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_RProveedorActionPerformed(evt);
            }
        });
        jMenu1.add(jMI_RProveedor);

        jMI_RProducto.setText("Registrar Producto");
        jMI_RProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_RProductoActionPerformed(evt);
            }
        });
        jMenu1.add(jMI_RProducto);

        jMI_RCompra.setText("Registrar Compra");
        jMI_RCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_RCompraActionPerformed(evt);
            }
        });
        jMenu1.add(jMI_RCompra);

        jMI_RConsumo.setText("Registrar Consumo");
        jMI_RConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_RConsumoActionPerformed(evt);
            }
        });
        jMenu1.add(jMI_RConsumo);

        jMI_RCosecha.setText("Registrar Cosecha");
        jMI_RCosecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_RCosechaActionPerformed(evt);
            }
        });
        jMenu1.add(jMI_RCosecha);

        jMI_Salir.setText("Salir");
        jMI_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_SalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMI_Salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ver");

        jMI_LProveedores.setText("Listado de Proveedores");
        jMI_LProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_LProveedoresActionPerformed(evt);
            }
        });
        jMenu2.add(jMI_LProveedores);

        jMI_LProductos.setText("Listado de Productos");
        jMI_LProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_LProductosActionPerformed(evt);
            }
        });
        jMenu2.add(jMI_LProductos);

        jMI_LCompras.setText("Listado de Compras");
        jMI_LCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_LComprasActionPerformed(evt);
            }
        });
        jMenu2.add(jMI_LCompras);

        jMI_LConsumos.setText("Listado de Consumos");
        jMI_LConsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_LConsumosActionPerformed(evt);
            }
        });
        jMenu2.add(jMI_LConsumos);

        jMI_LCosechas.setText("Listado de Cosechas");
        jMI_LCosechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_LCosechasActionPerformed(evt);
            }
        });
        jMenu2.add(jMI_LCosechas);

        jMI_LAreas.setText("Listado de Areas");
        jMI_LAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_LAreasActionPerformed(evt);
            }
        });
        jMenu2.add(jMI_LAreas);

        jMI_LUnidaddeMedida.setText("Listado Unidades de Medida");
        jMI_LUnidaddeMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_LUnidaddeMedidaActionPerformed(evt);
            }
        });
        jMenu2.add(jMI_LUnidaddeMedida);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_proveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_proveedoresMouseClicked
        RegistrarProveedor ventana = new RegistrarProveedor();
        mostrar.removeAll();
        mostrar.add(ventana);
        ventana.show();
    }//GEN-LAST:event_lbl_proveedoresMouseClicked

    private void lbl_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_productosMouseClicked
        RegistrarProducto ventana2 = new RegistrarProducto();
        mostrar.removeAll();
        mostrar.add(ventana2);
        ventana2.show();
    }//GEN-LAST:event_lbl_productosMouseClicked

    private void lbl_comprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_comprasMouseClicked
        RegistrarCompra ventana3 = new RegistrarCompra();
        mostrar.removeAll();
        mostrar.add(ventana3);
        ventana3.show();
    }//GEN-LAST:event_lbl_comprasMouseClicked

    private void lbl_consumosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_consumosMouseClicked
        RegistrarConsumo ventana4 = new RegistrarConsumo();
        mostrar.removeAll();
        mostrar.add(ventana4);
        ventana4.show();
    }//GEN-LAST:event_lbl_consumosMouseClicked

    private void lbl_cosechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cosechaMouseClicked
        RegistrarCosecha ventana5 = new RegistrarCosecha();
        mostrar.removeAll();
        mostrar.add(ventana5);
        ventana5.show();
    }//GEN-LAST:event_lbl_cosechaMouseClicked

    private void lbl_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_salirMouseClicked
        salir();
    }//GEN-LAST:event_lbl_salirMouseClicked

    private void jMI_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_SalirActionPerformed
        salir();
    }//GEN-LAST:event_jMI_SalirActionPerformed

    private void jMI_RProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_RProveedorActionPerformed
        RegistrarProveedor ventana = new RegistrarProveedor();
        mostrar.removeAll();
        mostrar.add(ventana);
        ventana.show();
    }//GEN-LAST:event_jMI_RProveedorActionPerformed

    private void jMI_RProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_RProductoActionPerformed
        RegistrarProducto ventana2 = new RegistrarProducto();
        mostrar.removeAll();
        mostrar.add(ventana2);
        ventana2.show();
    }//GEN-LAST:event_jMI_RProductoActionPerformed

    private void jMI_RCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_RCompraActionPerformed
        RegistrarCompra ventana3 = new RegistrarCompra();
        mostrar.removeAll();
        mostrar.add(ventana3);
        ventana3.show();
    }//GEN-LAST:event_jMI_RCompraActionPerformed

    private void jMI_RConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_RConsumoActionPerformed
        RegistrarConsumo ventana4 = new RegistrarConsumo();
        mostrar.removeAll();
        mostrar.add(ventana4);
        ventana4.show();
    }//GEN-LAST:event_jMI_RConsumoActionPerformed

    private void jMI_RCosechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_RCosechaActionPerformed
        RegistrarCosecha ventana5 = new RegistrarCosecha();
        if (JInternalFrames_Abiertos(ventana5) == false) {
            mostrar.removeAll();
            mostrar.add(ventana5);
            ventana5.show();
        }
    }//GEN-LAST:event_jMI_RCosechaActionPerformed

    private void lbl_reportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_reportesMouseClicked
        Reportes ventana6 = new Reportes();
        mostrar.removeAll();
        mostrar.add(ventana6);
        ventana6.show();
    }//GEN-LAST:event_lbl_reportesMouseClicked

    private void jMI_LProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_LProveedoresActionPerformed
        Frame listaProveedor = JOptionPane.getFrameForComponent(this);
        Fmr_ListadoProveedores abrir = new Fmr_ListadoProveedores(listaProveedor, true);
        abrir.setVisible(true);
    }//GEN-LAST:event_jMI_LProveedoresActionPerformed

    private void jMI_LProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_LProductosActionPerformed
        Frame ListaProductos = JOptionPane.getFrameForComponent(this);
        Fmr_ListadoProductos ventana = new Fmr_ListadoProductos(ListaProductos, false);
        ventana.setVisible(true);
    }//GEN-LAST:event_jMI_LProductosActionPerformed

    private void jMI_LComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_LComprasActionPerformed
        Frame ListaCompras = JOptionPane.getFrameForComponent(this);
        Fmr_ListadoCompras ventana = new Fmr_ListadoCompras(ListaCompras, true);
        ventana.setVisible(true);
    }//GEN-LAST:event_jMI_LComprasActionPerformed

    private void jMI_LConsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_LConsumosActionPerformed
        Frame ListaConsumos = JOptionPane.getFrameForComponent(this);
        Fmr_ListadoConsumos Consumo = new Fmr_ListadoConsumos(ListaConsumos, false);
        Consumo.setVisible(true);
    }//GEN-LAST:event_jMI_LConsumosActionPerformed

    private void jMI_LCosechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_LCosechasActionPerformed
        Frame ListaCosecha = JOptionPane.getFrameForComponent(this);
        Fmr_ListadoCosechas Cosecha = new Fmr_ListadoCosechas(ListaCosecha, true);
        Cosecha.show();
    }//GEN-LAST:event_jMI_LCosechasActionPerformed

    private void jMI_LAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_LAreasActionPerformed
        Frame Area = JOptionPane.getFrameForComponent(this);
        Fmr_ListadoArea ventana = new Fmr_ListadoArea(Area, true);
        ventana.show();
    }//GEN-LAST:event_jMI_LAreasActionPerformed

    private void jMI_LUnidaddeMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_LUnidaddeMedidaActionPerformed
        Frame ListadoUnidadMedida = JOptionPane.getFrameForComponent(this);
        Fmr_ListadoUnidadmedida ventana = new Fmr_ListadoUnidadmedida(ListadoUnidadMedida, false);
        ventana.setVisible(true);
    }//GEN-LAST:event_jMI_LUnidaddeMedidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem jMI_LAreas;
    private javax.swing.JMenuItem jMI_LCompras;
    private javax.swing.JMenuItem jMI_LConsumos;
    private javax.swing.JMenuItem jMI_LCosechas;
    private javax.swing.JMenuItem jMI_LProductos;
    private javax.swing.JMenuItem jMI_LProveedores;
    private javax.swing.JMenuItem jMI_LUnidaddeMedida;
    private javax.swing.JMenuItem jMI_RCompra;
    private javax.swing.JMenuItem jMI_RConsumo;
    private javax.swing.JMenuItem jMI_RCosecha;
    private javax.swing.JMenuItem jMI_RProducto;
    private javax.swing.JMenuItem jMI_RProveedor;
    private javax.swing.JMenuItem jMI_Salir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_compras;
    private javax.swing.JLabel lbl_consumos;
    private javax.swing.JLabel lbl_cosecha;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_productos;
    private javax.swing.JLabel lbl_proveedores;
    private javax.swing.JLabel lbl_reportes;
    private javax.swing.JLabel lbl_salir;
    public static javax.swing.JDesktopPane mostrar;
    // End of variables declaration//GEN-END:variables
}