/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios_emergentes;

import Conexion.conexion;
import Formularios.RegistrarProductos;
import static Formularios.RegistrarProductos.jDate_FechaVencimiento;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class Fmr_Listado_Productos extends javax.swing.JFrame {

    conexion conn = new conexion();
    Connection iniciarConexion = conn.conexion();

    public Fmr_Listado_Productos() {
        initComponents();
        MostrarlistadoProductos();
    }
//        public void EliminarDatosTabla (){ //SELECCIONAR DATOS DE LA TABLA Y PODER ELIMINARLO
//        try {
//            int filaSeleccionada= TablaCliente.getSelectedRow();
//            
//            String Sql="delete From Usuarios where Codigo = " + TablaCliente.getValueAt(filaSeleccionada,0);
//            
//            Statement st= iniciarConexion.createStatement();
//            
//            int n = st.executeUpdate(Sql);
//            
//            if (n>=0){
//                JOptionPane.showConfirmDialog(null, "Usuario eliminado Satisfactoriamente");
//                
//            }
//        } catch (Exception e){
//            JOptionPane.showConfirmDialog(null, "Error al Eliminar Usuario" + e.getMessage());
//        }
//        }

    public void MostrarlistadoProductos() {

        DefaultTableModel tcliente = new DefaultTableModel();
        tcliente.addColumn("Codigo");
        tcliente.addColumn("Nombre");
        tcliente.addColumn("Descripción");
        tcliente.addColumn("Ingrediente Activo");
        tcliente.addColumn("Fecha de Vencimiento");
        tcliente.addColumn("Unidad de Medida");
        tcliente.addColumn("Tipo de Producto");
                



        TablaCliente.setModel(tcliente);
            
        String[] datos = new String[7];

        try {
            Statement leer = iniciarConexion.createStatement();
            ResultSet resultado = leer.executeQuery("SELECT * FROM Productos");

            while (resultado.next()) {
                datos[0] = resultado.getString(1);
                datos[1] = resultado.getString(2);
                datos[2] = resultado.getString(3);
                datos[3] = resultado.getString(4);
                datos[4] = resultado.getString(5);
                datos[5] = resultado.getString(6);
                datos[6] = resultado.getString(7);
                
            
                
               
                tcliente.addRow(datos);
            }
            TablaCliente.setModel(tcliente);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + "Error en la Consulta");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCliente = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Descripcion", "Ingrediente Activo", "Fecha de Vencimiento", "Unidad de Medida", "Tipo de Producto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaCliente);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("Listado de Productos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jButton1)
                .addContainerGap(665, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(380, 380, 380))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TablaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaClienteMouseClicked
       
         if (evt.getClickCount () ==1){
             
             JTable receptor = (JTable) evt.getSource();
             RegistrarProductos.txt_codigoProducto.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),0).toString());
             RegistrarProductos.txt_nombreProducto.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),1).toString());
             RegistrarProductos.txt_descripcionProducto.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),2).toString());
             RegistrarProductos.txt_Ingredienteactivo.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),3).toString());
             RegistrarProductos.jDate_FechaVencimiento.setDateFormatString(receptor.getModel().getValueAt(receptor.getSelectedRow(),4).toString());
             RegistrarProductos.cbo_unidadMedida.setSelectedItem(receptor.getModel().getValueAt(receptor.getSelectedRow(),5).toString());
             RegistrarProductos.cbo_categoria.setSelectedItem(receptor.getModel().getValueAt(receptor.getSelectedRow(),6).toString());
             
             
           //  RegistrarProductos.cbo_unidadMedida.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),0).toString());
          //   RegistrarProductos.cbo_categoria.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),0).toString());
             
            
                                     
         }
    }//GEN-LAST:event_TablaClienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fmr_Listado_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fmr_Listado_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fmr_Listado_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fmr_Listado_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fmr_Listado_Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable TablaCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
}
