package Formularios_emergentes;

import Conexion.conexion;
import Formularios.RegistrarProducto;
import static Formularios.RegistrarProducto.txt_codigoProducto;
import java.awt.Component;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import java.awt.Graphics;
import java.awt.Image;

public final class Fmr_ListadoProductos extends javax.swing.JDialog {

    conexion conn = new conexion();
    Connection iniciarConexion = conn.conexion();

    public Fmr_ListadoProductos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("AgroControl - Lista de Productos");
        setLocationRelativeTo(null);

        MostrarlistadoProductos();
        bloquearListado();
    }

    public void MostrarlistadoProductos() {

        DefaultTableModel tcliente = new DefaultTableModel();
        tcliente.addColumn("Codigo");
        tcliente.addColumn("Nombre");
        tcliente.addColumn("Descripción");
        tcliente.addColumn("Ingrediente Activo");
        tcliente.addColumn("Fecha de Vencimiento");
        tcliente.addColumn("Unidad de Medida");
        tcliente.addColumn("Tipo de Producto");

        TablaCliente.setModel(tcliente);

        String[] datos = new String[7];

        try {
            Statement leer = iniciarConexion.createStatement();
            ResultSet resultado = leer.executeQuery("SELECT Codigo,Nombre,Descripcion,IngredienteActivo,FechadeVencimiento, unimedidatproducto.UnidaddeMedidaDato,tipodeproducto.TipodeProducto\n"
                    + "FROM Productos INNER JOIN tipodeproducto\n"
                    + "ON productos.TipodeProducto = tipodeproducto.idtipoproducto\n"
                    + "INNER JOIN unimedidatproducto ON productos.UnidaddeMedida = unimedidatproducto.IDuniMedida");

            while (resultado.next()) {
                datos[0] = resultado.getString(1);
                datos[1] = resultado.getString(2);
                datos[2] = resultado.getString(3);
                datos[3] = resultado.getString(4);
                datos[4] = resultado.getString(5);
                datos[5] = resultado.getString(6);
                datos[6] = resultado.getString(7);

                tcliente.addRow(datos);
            }
            TablaCliente.setModel(tcliente);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + "Error en la Consulta");
        }
    }

    public void BotonBuscar(String buscar) {

        DefaultTableModel tclientee = new DefaultTableModel();
        tclientee.addColumn("Codigo");
        tclientee.addColumn("Nombre");
        tclientee.addColumn("Descripcion");
        tclientee.addColumn("Ingrediente Activo");
        tclientee.addColumn("Fecha de Nacimiento");
        tclientee.addColumn("Unidad de Medida");
        tclientee.addColumn("Tipo de Producto");

        TablaCliente.setModel(tclientee);

        String[] datos = new String[7];

        try {
            Statement leer = iniciarConexion.createStatement();
            ResultSet resultado = leer.executeQuery("SELECT * FROM Productos WHERE Codigo  LIKE '%" + buscar + "%' OR Nombre LIKE '%" + buscar + "%'  OR IngredienteActivo LIKE '%" + buscar + "%' OR UnidaddeMedida LIKE '%" + buscar + "%' OR TipodeProducto LIKE '%" + buscar + "%'  OR FechadeVencimiento LIKE '%" + buscar + "%'");

            while (resultado.next()) {
                datos[0] = resultado.getString(1);
                datos[1] = resultado.getString(2);
                datos[2] = resultado.getString(3);
                datos[3] = resultado.getString(4);
                datos[4] = resultado.getString(5);
                datos[5] = resultado.getString(6);
                datos[6] = resultado.getString(7);

                tclientee.addRow(datos);
            }
            TablaCliente.setModel(tclientee);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + "Error en la Consulta");
        }
    }

    public void verificarcodigo() {

        for (int i = 0; i < TablaCliente.getRowCount(); i++) {

            if (TablaCliente.getValueAt(i, 1).equals(txt_codigoProducto.getText())) {
                JOptionPane.showMessageDialog(null, "El Codigo ya Existe");

            }

        }

    }

    public void bloquearListado() {

        for (Component a : TablaCliente.getComponents()) {
            a.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon1 = new ImageIcon(getClass().getResource("/Imagenes/fondo-submenu2.jpg"));
        Image image1 = icon1.getImage();
        jDP_ListaProductos = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image1,0,0,getWidth(),getHeight(),this);
            }
        }
        ;
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCliente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jDP_ListaProductos.setBackground(new java.awt.Color(255, 255, 255));

        TablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaCliente);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("Listado de Productos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Buscar:");

        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });

        jDP_ListaProductos.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDP_ListaProductos.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDP_ListaProductos.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDP_ListaProductos.setLayer(txt_buscar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDP_ListaProductosLayout = new javax.swing.GroupLayout(jDP_ListaProductos);
        jDP_ListaProductos.setLayout(jDP_ListaProductosLayout);
        jDP_ListaProductosLayout.setHorizontalGroup(
            jDP_ListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDP_ListaProductosLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jDP_ListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDP_ListaProductosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDP_ListaProductosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(276, 276, 276))
        );
        jDP_ListaProductosLayout.setVerticalGroup(
            jDP_ListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDP_ListaProductosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jDP_ListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDP_ListaProductos)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDP_ListaProductos, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaClienteMouseClicked

        if (evt.getClickCount() == 1) {

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

            String fechavencimiento = TablaCliente.getValueAt(TablaCliente.getSelectedRow(), 4).toString().trim();
            Date dato = null;

            try {
                dato = (Date) formato.parse(fechavencimiento);
                RegistrarProducto.jDate_FechaVencimiento.setDate(dato);

            } catch (Exception e) {

            }

            RegistrarProducto.txt_codigoProducto.setText(TablaCliente.getModel().getValueAt(TablaCliente.getSelectedRow(), 0).toString());
            RegistrarProducto.txt_nombreProducto.setText(TablaCliente.getModel().getValueAt(TablaCliente.getSelectedRow(), 1).toString());
            RegistrarProducto.txt_descripcionProducto.setText(TablaCliente.getModel().getValueAt(TablaCliente.getSelectedRow(), 2).toString());
            RegistrarProducto.txt_Ingredienteactivo.setText(TablaCliente.getModel().getValueAt(TablaCliente.getSelectedRow(), 3).toString());
            RegistrarProducto.cbo_unidadMedida.setSelectedItem(TablaCliente.getModel().getValueAt(TablaCliente.getSelectedRow(), 5).toString());
            RegistrarProducto.cbo_categoria.setSelectedItem(TablaCliente.getModel().getValueAt(TablaCliente.getSelectedRow(), 6).toString());

        }
        this.hide();
        RegistrarProducto.btn_eliminar.setEnabled(true);
        RegistrarProducto.btn_editar.setEnabled(true);
    }//GEN-LAST:event_TablaClienteMouseClicked

    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased
        BotonBuscar(txt_buscar.getText());
    }//GEN-LAST:event_txt_buscarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fmr_ListadoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fmr_ListadoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fmr_ListadoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fmr_ListadoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Fmr_ListadoProductos dialog = new Fmr_ListadoProductos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable TablaCliente;
    private javax.swing.JDesktopPane jDP_ListaProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
